### ISSUE TITLE
ModuleNotFoundError: No module named 'mAPEvaluate'

### ISSUE THREAD

**Issue by scjdff** [CaptainEven/MyNanoDet#1]
Traceback (most recent call last):
  File "tools/train.py", line 15, in <module>
    from nanodet.evaluator import build_evaluator
  File "/home/ubuntu/ncnn/MyNanoDet/nanodet/evaluator/__init__.py", line 1, in <module>
    from .coco_detection import CocoDetectionEvaluator, MyDetectionEvaluator
  File "/home/ubuntu/ncnn/MyNanoDet/nanodet/evaluator/coco_detection.py", line 5, in <module>
    from mAPEvaluate.TestmApDetect import test_tmp_mAP
have  a problem test_tmp_mAP does not exist

**Comment by CaptainEven** [comment]
@scjdff Updated now, plz check.
